spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123
    url: jdbc:mysql://localhost:3306/demo?characterEncoding=utf-8&useSSL=false
  thymeleaf:
    prefix: classpath:/templates/

#url相关
projecturl:
  wechatMpAuthorize: http://tscc.natapp1.cc
  pullUserMsgPrefix: https://api.weixin.qq.com/sns/userinfo?access_token=

#微信相关
wechat:
  mpAppId: wx036b4158120b15c1
  mpAppSecret: 480ca4b55c86310af4bf3b3b34f9ecb5

# 自定义文件上传路径
web:
  upload-path: D:/test/

